version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands: 
      - docker-compose -v
      - docker version
  pre_build:
    commands:
      - echo Build Start
      - docker-compose -f docker_compose_test.yml build
      - echo Build Finish
      - echo webpacker install start
      - docker-compose -f docker_compose_test.yml run app rails webpacker:install
  build:
    commands:
      - docker-compose -f docker_compose_test.yml up -d
      - docker exec -it app sh && rails db:migrate