version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands: 
  pre_build:
    commands:
      - echo PRE_BUILD Start
      - docker-compose -f docker_compose_test.yml build
      - docker-compose -f docker_compose_test.yml up -d
      - docker-compose -f docker_compose_test.yml run app rails db:create
      - docker-compose -f docker_compose_test.yml run app rails db:migrate
      - docker-compose -f docker_compose_test.yml run app rails assets:precompile
  build:
    commands:
      - echo BUILD start
      - docker-compose -f docker_compose_test.yml run app bundle exec rake spec
