version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0 # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/mysql:/var/lib/mysql:delegated
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: 'app'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db