version: '3.8'
services:
  app:
    build: .
    environment:
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
    container_name: 'app'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  redis:
    image: redis
    container_name: 'redis'
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  worker:
    build: .
    container_name: 'worker'
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - .:/app
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      RESQUE_HOST_DEVELOPMENT: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379