Resources:

 #=================================
 # VPCの作成
 #=================================
  miraVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: mira-vpc

#=================================
 # インターネットゲートウェイの作成
 #=================================
  miraInternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value: mira-igw

  miraAttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref miraInternetGateway
      VpcId: !Ref miraVPC

 #=================================
 # NATゲートウェイの作成
 #=================================
  miraNata:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt miraEIPNata.AllocationId
      SubnetId: !Ref miraSubnet01a
      Tags:
      - Key: Name
        Value: mira-nat-a

  miraEIPNata:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

#=================================
 # サブネットの作成
 #=================================
  miraSubnet01a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.0.0/24
      Tags:
      - Key: Name
        Value: subnet01a
      VpcId: !Ref miraVPC

  miraSubnet02a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.1.0/24
      Tags:
      - Key: Name
        Value: subnet02a
      VpcId: !Ref miraVPC

  miraSubnet03a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.2.0/24
      Tags:
      - Key: Name
        Value: subnet03a
      VpcId: !Ref miraVPC

 #=================================
 # ルートテーブルの作成
 #=================================
  miraRouteTable01:
    Type: "AWS::EC2::RouteTable"
    Properties:
      Tags:
      - Key: Name
        Value: mira01
      VpcId: !Ref miraVPC

  miraRouteTableAssociation01a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref miraRouteTable01
      SubnetId: !Ref miraSubnet01a

  miraRoute01:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref miraInternetGateway
      RouteTableId: !Ref miraRouteTable01
